name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:
    description: GITHUB_TOKEN or a PAT for the repository
    default: ${{ github.token }}
  issue:
    description: 'Issue number'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
