name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  issue:
    description: 'Issue number'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
